apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: laptop
  namespace: argocd
spec:
  destination:
    name: in-cluster
  project: default
  source:
    path: apps
    repoURL: https://github.com/wojtekidd/managed-argocd-lab
    targetRevision: HEAD
