apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/wojtekidd/managed-argocd-lab'
    targetRevision: HEAD
  destination:
    namespace: guestbook
    name: laptop
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
